import forest from '../../Assets/forestTrip.jpg';
import desert from '../../Assets/desertTrip.jpg';
import canyon from '../../Assets/canyonTrip.jpg';
import snow from '../../Assets/snowTrip.jpg';

export const productItems = [
	{
		title: 'Forest',
		adress: 'Test Adress',
		distance: '1000KM',
		price: '150$',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Perferendis optio deserunt, dolor fugit corrupti nesciunt modi repellendus explicabo ea asperiores natus totam qui quia molestias consequatur architecto harum, ipsum hic! Accusamus excepturi alias aperiam libero voluptates impedit aliquid, mollitia itaque possimus? Voluptatibus est eos impedit culpa magnam nam delectus? Tempore reprehenderit saepe excepturi. Qui temporibus assumenda, quibusdam necessitatibus accusantium cupiditate voluptate voluptatem? Totam omnis cum in tenetur vero iusto ratione veritatis? Molestiae blanditiis omnis saepe et error laborum hic numquam velit quaerat explicabo ut, dolores quos maxime at, facere porro ab voluptas molestias recusandae ipsum? Impedit quasi delectus eum beatae.',
		detailedTitle: 'Get the full expirience stay 7 days',
		detailedText: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consequuntur accusantium perspiciatis praesentium nobis earum porro deserunt expedita similique, blanditiis dolorum?',
		detailedPrice: '1050$ for 7 days',
		src1: forest,
		altText1: 'trees-on-forest-at-daytime',
		src2: forest,
		altText2: 'trees-on-forest-at-daytime',
		src3: forest,
		altText3: 'trees-on-forest-at-daytime',
		src4: forest,
		altText4: 'trees-on-forest-at-daytime',
		src5: forest,
		altText5: 'trees-on-forest-at-daytime',
		src6: forest,
		altText6: 'trees-on-forest-at-daytime',
	},
	{
		title: 'Desert',
		adress: 'Test Adress',
		distance: '1000KM',
		price: '150$',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Perferendis optio deserunt, dolor fugit corrupti nesciunt modi repellendus explicabo ea asperiores natus totam qui quia molestias consequatur architecto harum, ipsum hic! Accusamus excepturi alias aperiam libero voluptates impedit aliquid, mollitia itaque possimus? Voluptatibus est eos impedit culpa magnam nam delectus? Tempore reprehenderit saepe excepturi. Qui temporibus assumenda, quibusdam necessitatibus accusantium cupiditate voluptate voluptatem? Totam omnis cum in tenetur vero iusto ratione veritatis? Molestiae blanditiis omnis saepe et error laborum hic numquam velit quaerat explicabo ut, dolores quos maxime at, facere porro ab voluptas molestias recusandae ipsum? Impedit quasi delectus eum beatae.',
		detailedTitle: 'Get the full expirience stay 7 days',
		detailedText: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consequuntur accusantium perspiciatis praesentium nobis earum porro deserunt expedita similique, blanditiis dolorum?',
		detailedPrice: '1050$ for 7 days',
		src1: desert,
		altText1: 'desert',
		src2: desert,
		altText2: 'desert',
		src3: desert,
		altText3: 'desert',
		src4: desert,
		altText4: 'desert',
		src5: desert,
		altText5: 'desert',
		src6: desert,
		altText6: 'desert',
	},
	{
		title: 'Snow',
		adress: 'Test Adress',
		distance: '1000KM',
		price: '150$',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Perferendis optio deserunt, dolor fugit corrupti nesciunt modi repellendus explicabo ea asperiores natus totam qui quia molestias consequatur architecto harum, ipsum hic! Accusamus excepturi alias aperiam libero voluptates impedit aliquid, mollitia itaque possimus? Voluptatibus est eos impedit culpa magnam nam delectus? Tempore reprehenderit saepe excepturi. Qui temporibus assumenda, quibusdam necessitatibus accusantium cupiditate voluptate voluptatem? Totam omnis cum in tenetur vero iusto ratione veritatis? Molestiae blanditiis omnis saepe et error laborum hic numquam velit quaerat explicabo ut, dolores quos maxime at, facere porro ab voluptas molestias recusandae ipsum? Impedit quasi delectus eum beatae.',
		detailedTitle: 'Get the full expirience stay 7 days',
		detailedText: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consequuntur accusantium perspiciatis praesentium nobis earum porro deserunt expedita similique, blanditiis dolorum?',
		detailedPrice: '1050$ for 7 days',
		src1: snow,
		altText1: 'a-rare-sight-of-moraine-lake-in-winter',
		src2: snow,
		altText2: 'a-rare-sight-of-moraine-lake-in-winter',
		src3: snow,
		altText3: 'a-rare-sight-of-moraine-lake-in-winter',
		src4: snow,
		altText4: 'a-rare-sight-of-moraine-lake-in-winter',
		src5: snow,
		altText5: 'a-rare-sight-of-moraine-lake-in-winter',
		src6: snow,
		altText6: 'a-rare-sight-of-moraine-lake-in-winter',
	},
	{
		title: 'Canyon',
		adress: 'Test Adress',
		distance: '1000KM',
		price: '150$',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Perferendis optio deserunt, dolor fugit corrupti nesciunt modi repellendus explicabo ea asperiores natus totam qui quia molestias consequatur architecto harum, ipsum hic! Accusamus excepturi alias aperiam libero voluptates impedit aliquid, mollitia itaque possimus? Voluptatibus est eos impedit culpa magnam nam delectus? Tempore reprehenderit saepe excepturi. Qui temporibus assumenda, quibusdam necessitatibus accusantium cupiditate voluptate voluptatem? Totam omnis cum in tenetur vero iusto ratione veritatis? Molestiae blanditiis omnis saepe et error laborum hic numquam velit quaerat explicabo ut, dolores quos maxime at, facere porro ab voluptas molestias recusandae ipsum? Impedit quasi delectus eum beatae.',
		detailedTitle: 'Get the full expirience stay 7 days',
		detailedText: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consequuntur accusantium perspiciatis praesentium nobis earum porro deserunt expedita similique, blanditiis dolorum?',
		detailedPrice: '1050$ for 7 days',
		src1: canyon,
		altText1: 'rock-formation',
		src2: canyon,
		altText2: 'rock-formation',
		src3: canyon,
		altText3: 'rock-formation',
		src4: canyon,
		altText4: 'rock-formation',
		src5: canyon,
		altText5: 'rock-formation',
		src6: canyon,
		altText6: 'rock-formation',
	},
];
